server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost/banking_application
    driverClassName: org.postgresql.Driver
    username: banking
    password: ba nking
    platform: org.hibernate.dialect.Postgresql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
# To resolve the spring box error
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
