server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost/banking_application
    driverClassName: org.postgresql.Driver
    username:
    password:
    platform: org.hibernate.dialect.Postgresql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
# To resolve the spring box error
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher